import Head from "next/head";
import Image from "next/image";
import React, { useEffect, useState } from "react";


export default function Home() {
    React.useEffect(() => {
        window.addEventListener('scroll', changeColor)
    }, []);

    const [color, setColor] = useState(false)

    const changeColor = () => {
        if (window.scrollY >= window.innerHeight) {
            setColor(true)
        } else {
            setColor(false)
        }
    }

    const bgstyle = {
        backgroundImage: "url('/media/experienceshero.jpg')",
        height: '100vh',
        backgroundAttachment: 'fixed'
    }

    const itemstyle1 = {
        backgroundImage: "url('/media/experiencesbg.png')",
        height: '100%',
    }
    const itemstyle2 = {
        backgroundImage: "url('/media/experiencesbgi.png')",
        height: '100%',
    }


    return (
        <>
            <Head>
                <title>Incoming India | Contact</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <section className="text-black text-center">
                    <div className="bg-cover bg-center bg-no-repeat flex items-center justify-center" style={bgstyle}>
                        <div className="text-center px-2">
                            <h1 className="md:text-6xl text-4xl font-poppins font-semibold tracking-wide text-white hero-shadow">Experience India</h1>
                            <p className="font-poppins font-semibold md:text-2xl max-w-screen-md pt-2 text-[1.2rem] text-white hero-shadow">Discover the vibrant colors, flavors, and traditions of India's rich cultural tapestry - a journey you'll never forget!</p>
                        </div>
                    </div>
                    <nav className={`${color ? ' fixed top-[60px] lg:h-[30px] h-[50px] bg-white right-0 left-0' : 'h-[60px]'} bg-white z-10 w-[100full] flex justify-center items-center font-serifjp`}>
                        <ul className='lg:flex flex-row justify-center md:space-x-12 text-xs sm:text-md lg:text-md xl:text-lg'>
                            <div className='justify-center flex '>
                                <div className='lg:space-x-12 space-x-5 flex'>
                                    <li className={` cursor-pointer hover:text-orange-500 hover:border-b-2 hover:border-b-orange-500`}> <a href="#cuisines">Cuisines</a></li>
                                    <li className={` cursor-pointer hover:text-orange-500 hover:border-b-2 hover:border-b-orange-500`}><a href="#mountains">Mountains</a></li>
                                    <li className={` cursor-pointer hover:text-orange-500 hover:border-b-2 hover:border-b-orange-500`}> <a href="#trains">Royalty</a></li>
                                    <li className={` cursor-pointer hover:text-orange-500 hover:border-b-2 hover:border-b-orange-500`}> <a href="#forts-temples">Forts</a></li>
                                    <li className={` cursor-pointer hover:text-orange-500 hover:border-b-2 hover:border-b-orange-500`}> <a href="#wildlife">Wildlife</a></li>
                                </div>
                            </div>
                            <div className=' lg:space-x-12 space-x-5 flex'>
                                <li className={`cursor-pointer hover:text-orange-500 hover:border-b-2 hover:border-b-orange-500`} > <a href="#healing">Healing</a></li>
                                <li className={`cursor-pointer hover:text-orange-500 hover:border-b-2 hover:border-b-orange-500`} > <a href="#oceans">Oceans</a></li>
                                <li className={`cursor-pointer hover:text-orange-500 hover:border-b-2 hover:border-b-orange-500`} > <a href="#lakes">Lakes & Boats</a></li>
                                <li className={`cursor-pointer hover:text-orange-500 hover:border-b-2 hover:border-b-orange-500`} > <a href="#honeymoon">Honeymoon</a></li>
                                <li className={`cursor-pointer hover:text-orange-500 hover:border-b-2 hover:border-b-orange-500`} > <a href="#family">Family</a></li>
                            </div>
                        </ul>
                    </nav >


                    <div style={itemstyle2} className="h-[50vh] bg-blue-300   bg-cover bg-center bg-no-repeat" id='mountains'>
                        <div className="flex-row-reverse md:flex">
                            <img src='/media/mountains.jpg' className="md:hidden object-cover md:h-[70vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                            <div className="w-full md:w-1/2 px-2 ">
                                <h1 className="text-center md:py-10 py-5 text-3xl md:text-5xl text-black hero- font-poppins font-semibold">Himalayas & Mountains</h1>
                                <div className="flex justify-center">
                                    <div className="border-b-[3px] border-b-indigo-900 w-1/2 mb-5 md:mb-10"></div>
                                </div>
                                <p className="text-lg md:text-xl md:px-10 px-2">
                                    India is a treasure trove of majestic mountains that offer some of the most breathtaking views in the world. Mountain tours in India are a must-do for adventure enthusiasts, with options like trekking in the Himalayas, exploring the Western Ghats or climbing the peaks in the North-Eastern states. These tours offer an opportunity to experience the diverse landscape and culture of India. The tours are led by experienced guides who provide insights into the local flora and fauna, customs, and traditions. With cozy homestays and campsite accommodations, these tours allow you to experience the mountains up close and personal, making for a truly unforgettable adventure.
                                </p>

                                {/* <div className="flex items-center justify-center pt-5">
                                    <button className="text-lg  text-white bg-indigo-800 py-2 px-5 rounded-md mb-5">Explore More!</button>
                                </div> */}
                            </div>
                            <img src='/media/mountains.jpg' className="md:block hidden object-cover md:h-[70vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                        </div>
                    </div>


                    <div style={itemstyle1} className=" bg-blue-300   bg-cover bg-center bg-no-repeat " id="cuisines">
                        <div className="flex-row md:flex">
                            <img src='/media/food.jpg' className="md:hidden object-cover md:h-[70vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                            <div className="w-full md:w-1/2 px-2 ">
                                <h1 className="text-center md:py-10 py-5 text-3xl md:text-5xl text-black hero- font-poppins font-semibold">Delicious Indian Cuisines</h1>
                                <div className="flex justify-center">
                                    <div className="border-b-[3px] border-b-indigo-900 w-1/2 mb-5 md:mb-10"></div>
                                </div>
                                <p className="text-lg md:text-xl md:px-10 px-2">
                                    India is a food lover's paradise, offering a diverse range of delicious cuisines that vary from region to region. From the tangy and spicy street food of Mumbai to the rich and aromatic curries of North India, Indian cuisine is a delight for the taste buds. The use of spices and herbs, along with a variety of cooking techniques, gives each dish a unique flavor and aroma. Vegetarian cuisine is a specialty of India, with a range of dishes like dal, paneer, and chole that are loved by locals and visitors alike. The diversity of Indian cuisine makes it a must-try for food enthusiasts visiting the country.                                </p>

                                {/* <div className="flex items-center justify-center pt-5">
                                    <button className="text-lg  text-white bg-indigo-800 py-2 px-5 rounded-md mb-5">Explore More!</button>
                                </div> */}
                            </div>
                            <img src='/media/food.jpg' className="md:block hidden object-cover md:h-[70vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                        </div>
                    </div>


                    <div style={itemstyle2} className=" bg-blue-300   bg-cover bg-center bg-no-repeat " id="trains">
                        <div className="flex-row md:flex">
                            <img src='/media/train.jpg' className=" object-cover md:h-[70vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                            <div className="w-full md:w-1/2 px-2 ">
                                <h1 className="text-center md:py-10 py-5 text-3xl md:text-5xl text-black hero- font-poppins font-semibold">Train Packages</h1>
                                <div className="flex justify-center">
                                    <div className="border-b-[3px] border-b-indigo-900 w-1/2 mb-5 md:mb-10"></div>
                                </div>
                                <p className="text-lg md:text-xl md:px-10 px-2">
                                    India is a land of diverse landscapes, cultures, and traditions, making it a perfect honeymoon destination. With a plethora of options available, honeymoon packages in India cater to every need, whether you want a relaxing beach vacation or an adventurous mountain trek. The country's rich heritage and vibrant culture offer a unique and unforgettable experience for newlyweds. From the romantic backwaters of Kerala to the majestic forts of Rajasthan, India has something for everyone. Indulge in luxurious accommodations, delicious cuisine, and create memories to last a lifetime with your loved one.
                                </p>

                                {/* {/* <div className="flex items-center justify-center pt-5">
                                    <button className="text-lg text-white bg-indigo-800 py-2 px-5 rounded-md mb-5">Explore More!</button>
                                </div> */}
                            </div>
                        </div>
                    </div>


                    <div style={itemstyle2} className="h-[50vh] bg-blue-300   bg-cover bg-center bg-no-repeat" id='forts-temples'>
                        <div className="flex-row md:flex">
                            <img src='/media/forts.jpg' className=" md:hidden object-cover md:h-[70vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                            <div className="w-full md:w-1/2 px-2 ">
                                <h1 className="text-center md:py-10 py-5 text-3xl md:text-5xl text-black hero- font-poppins font-semibold">Forts, Palaces and Temples</h1>
                                <div className="flex justify-center">
                                    <div className="border-b-[3px] border-b-indigo-900 w-1/2 mb-5 md:mb-10"></div>
                                </div>
                                <p className="text-lg md:text-xl md:px-10 px-2">
                                    Train tours in India are a unique and luxurious way to explore the country's rich cultural heritage and diverse landscape. The opulent trains like the Palace on Wheels, Maharajas' Express, and Deccan Odyssey offer five-star accommodations, exquisite dining, and exceptional service. The tours take you to some of the most iconic destinations in India, including the Taj Mahal, Rajasthan's royal cities, and the wildlife sanctuaries of Central India. The onboard amenities like spas, bars, and lounges ensure a comfortable and memorable journey. These tours offer a glimpse into India's rich history, architecture, and culture, making it an experience of a lifetime.
                                </p>

                                {/* <div className="flex items-center justify-center pt-5">
                                    <button className="text-lg text-white bg-indigo-800 py-2 px-5 rounded-md mb-5">Explore More!</button>
                                </div> */}
                            </div>
                            <img src='/media/forts.jpg' className="md:block hidden object-cover md:h-[70vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                        </div>
                    </div>






                    <div style={itemstyle1} className=" bg-blue-300   bg-cover bg-center bg-no-repeat " id="wildlife">
                        <div className="flex-row md:flex">
                            <img src='/media/wildlife.jpg' className=" object-cover md:h-[70vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                            <div className="w-full md:w-1/2 px-2 ">
                                <h1 className="text-center md:py-10 py-5 text-3xl md:text-5xl text-black hero- font-poppins font-semibold">Wildlife Experiences</h1>
                                <div className="flex justify-center">
                                    <div className="border-b-[3px] border-b-indigo-900 w-1/2 mb-5 md:mb-10"></div>
                                </div>
                                <p className="text-lg md:text-xl md:px-10 px-2">
                                    Wildlife tours in India are a thrilling way to explore the country's rich biodiversity and natural beauty. India is home to a vast array of wildlife, including tigers, elephants, lions, rhinoceros, and many more. The wildlife tours take you to some of the most iconic national parks and wildlife sanctuaries, including Ranthambore, Bandhavgarh, and Kanha. These tours provide an opportunity to witness animals in their natural habitat, guided by experienced naturalists and trackers. The tours also offer an opportunity to experience the local culture and cuisine, making it a unique and unforgettable experience. Whether you're a nature lover or an adventure enthusiast, wildlife tours in India are a must-do.
                                </p>

                                {/* <div className="flex items-center justify-center pt-5">
                                    <button className="text-lg text-white bg-indigo-800 py-2 px-5 rounded-md mb-5">Explore More!</button>
                                </div> */}
                            </div>
                        </div>
                    </div>


                    <div style={itemstyle2} className="h-[50vh] bg-blue-300   bg-cover bg-center bg-no-repeat" id="healing">
                        <div className="flex-row md:flex">
                            <img src='/media/yoga.jpg' className="md:hidden object-cover md:h-[70vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                            <div className="w-full md:w-1/2 px-2 ">
                                <h1 className="text-center md:py-10 py-5 text-3xl md:text-5xl text-black hero- font-poppins font-semibold">Inner Peace</h1>
                                <div className="flex justify-center">
                                    <div className="border-b-[3px] border-b-indigo-900 w-1/2 mb-5 md:mb-10"></div>
                                </div>
                                <p className="text-lg md:text-xl md:px-10 px-2">
                                    Nestled in the lap of the Himalayas, India offers a plethora of options for those seeking to deepen their yoga and meditation practice. From the serene beaches of Goa to the peaceful backwaters of Kerala, there are numerous locations to choose from. However, Rishikesh stands out as a mecca for yoga and meditation enthusiasts. With a rich spiritual heritage and a wide range of yoga and meditation retreats, Rishikesh has something for everyone. Whether you're a beginner or an advanced practitioner, Rishikesh provides an ideal environment for deepening your practice and exploring the spiritual side of yoga and meditation.
                                </p>

                                {/* <div className="flex items-center justify-center pt-5">
                                    <button className="text-lg text-white bg-indigo-800 py-2 px-5 rounded-md mb-5">Explore More!</button>
                                </div> */}
                            </div>
                            <img src='/media/yoga.jpg' className="md:block hidden object-cover md:h-[70vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                        </div>
                    </div>


                    <div style={itemstyle1} className=" bg-blue-300   bg-cover bg-center bg-no-repeat " id="oceans">
                        <div className="flex-row md:flex">
                            <img src='/media/beech.jpg' className=" object-cover md:h-[70vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                            <div className="w-full md:w-1/2 px-2 ">
                                <h1 className="text-center md:py-10 py-5 text-3xl md:text-5xl text-black hero- font-poppins font-semibold">Beaches & Islands</h1>
                                <div className="flex justify-center">
                                    <div className="border-b-[3px] border-b-indigo-900 w-1/2 mb-5 md:mb-10"></div>
                                </div>
                                <p className="text-lg md:text-xl md:px-10 px-2">
                                    India is home to some of the most spectacular beaches and islands, making it a popular destination for beach lovers and adventure enthusiasts. The beaches of Goa, Kerala, and Andaman and Nicobar Islands are renowned for their natural beauty and serenity. The turquoise waters, pristine sand, and palm-lined shores provide an idyllic setting for relaxation and rejuvenation. The islands of Andaman and Nicobar offer a unique blend of adventure and relaxation, with activities like scuba diving, snorkeling, and sea-walking. The tours provide an opportunity to experience the local culture and cuisine, making it a memorable and authentic experience. Whether you're seeking solitude or adventure, beach and island tours in India offer a perfect getaway.
                                </p>

                                {/* <div className="flex items-center justify-center pt-5">
                                    <button className="text-lg text-white bg-indigo-800 py-2 px-5 rounded-md mb-5">Explore More!</button>
                                </div> */}
                            </div>
                        </div>
                    </div>





                    <div style={itemstyle2} className="h-[50vh] bg-blue-300   bg-cover bg-center bg-no-repeat" id="lakes">
                        <div className="flex-row md:flex">
                            <img src='/media/houseboats.jpg' className="md:hidden object-cover md:h-[70vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                            <div className="w-full md:w-1/2 px-2 ">
                                <h1 className="text-center md:py-10 py-5 text-3xl md:text-5xl text-black hero- font-poppins font-semibold">Lakes & Houseboats</h1>
                                <div className="flex justify-center">
                                    <div className="border-b-[3px] border-b-indigo-900 w-1/2 mb-5 md:mb-10"></div>
                                </div>
                                <p className="text-lg md:text-xl md:px-10 px-2">
                                    India is home to some of the most beautiful lakes, making it a perfect destination for those seeking to enjoy the serene beauty of nature. The famous lakes in Udaipur, Nainital, and Kashmir are known for their stunning natural beauty and offer a perfect setting for relaxation and rejuvenation. Houseboats and cruises in India provide an opportunity to explore the picturesque landscapes and experience the local culture. The houseboats in the backwaters of Kerala provide a unique and luxurious experience, while river cruises in the Brahmaputra and Ganges offer a chance to explore the scenic beauty of India's waterways. Whether you're seeking a relaxing vacation or an adventure, the lakes, houseboats, and cruises in India offer a perfect escape.                                </p>

                                {/* <div className="flex items-center justify-center pt-5">
                                    <button className="text-lg text-white bg-indigo-800 py-2 px-5 rounded-md mb-5">Explore More!</button>
                                </div> */}
                            </div>
                            <img src='/media/houseboats.jpg' className="md:block hidden object-cover md:h-[70vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                        </div>
                    </div>

                    <div style={itemstyle1} className=" bg-blue-300   bg-cover bg-center bg-no-repeat " id="honeymoon">
                        <div className="flex-row md:flex">
                            <img src='/media/honeymoon.jpg' className=" object-cover md:h-[70vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                            <div className="w-full md:w-1/2 px-2 ">
                                <h1 className="text-center md:py-10 py-5 text-3xl md:text-5xl text-black hero- font-poppins font-semibold ">Honeymoon Packages</h1>
                                <div className="flex justify-center">
                                    <div className="border-b-[3px] border-b-indigo-900 w-1/2 mb-5 md:mb-10"></div>
                                </div>
                                <p className="text-lg md:text-xl md:px-10 px-2">
                                    India is a land of diverse landscapes, cultures, and traditions, making it a perfect honeymoon destination. With a plethora of options available, honeymoon packages in India cater to every need, whether you want a relaxing beach vacation or an adventurous mountain trek. The country's rich heritage and vibrant culture offer a unique and unforgettable experience for newlyweds. From the romantic backwaters of Kerala to the majestic forts of Rajasthan, India has something for everyone. Indulge in luxurious accommodations, delicious cuisine, and create memories to last a lifetime with your loved one.
                                </p>

                                {/* <div className="flex items-center justify-center pt-5">
                                    <button className="text-lg text-white bg-indigo-800 py-2 px-5 rounded-md mb-5">Explore More!</button>
                                </div> */}
                            </div>
                        </div>
                    </div>

                    <div style={itemstyle2} className="h-[50vh] bg-blue-300   bg-cover bg-center bg-no-repeat" id='family'>
                        <div className="flex-row md:flex">
                            <img src='/media/family.jpg' className="md:hidden object-cover md:h-[70vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                            <div className="w-full md:w-1/2 px-2 ">
                                <h1 className="text-center md:py-10 py-5 text-3xl md:text-5xl text-black hero- font-poppins font-semibold">Family Time & Travel</h1>
                                <div className="flex justify-center">
                                    <div className="border-b-[3px] border-b-indigo-900 w-1/2 mb-5 md:mb-10"></div>
                                </div>
                                <p className="text-lg md:text-xl md:px-10 px-2">
                                    Travelling with family in India can be a delightful experience, offering an opportunity to bond and create unforgettable memories. The country's diverse landscape and rich cultural heritage provide a perfect backdrop for family adventures. From the iconic monuments of Delhi, Agra, and Jaipur to the serene backwaters of Kerala, India offers a range of destinations to choose from. The family-friendly tours provide an opportunity to experience local culture, food, and customs, creating a learning experience for children. With a range of accommodations, from budget-friendly to luxurious, travelling with family in India is comfortable and affordable. The warm hospitality and friendly locals make India a perfect destination for family travel.                                </p>

                                {/* <div className="flex items-center justify-center pt-5">
                                    <button className="text-lg text-white bg-indigo-800 py-2 px-5 rounded-md mb-5">Explore More!</button>
                                </div> */}
                            </div>
                            <img src='/media/family.jpg' className="hidden md:block object-cover md:h-[70vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                        </div>
                    </div>
                    {/* <div style={itemstyle1} className=" bg-blue-300   bg-cover bg-center bg-no-repeat ">
                        <div className="flex-row md:flex">
                            <img src='/media/food.jpg' className=" object-cover md:h-[70vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                            <div className="w-full md:w-1/2 px-2 ">
                                <h1 className="text-center md:py-10 py-5 text-3xl md:text-5xl text-black hero- font-poppins font-semibold">Honeymoon Packages</h1>
                            </div>
                        </div>
                    </div> */}


                    {/* <div style={itemstyle2} className="h-[50vh] bg-blue-300   bg-cover bg-center bg-no-repeat">
                        <div className="flex-row md:flex">
                            <div className="w-full md:w-1/2 px-2 ">
                                <h1 className="text-center md:py-10 py-5 text-3xl md:text-5xl text-black hero- font-poppins font-semibold">Honeymoon Packages</h1>
                            </div>
                            <img src='/media/mountains.jpg' className=" object-cover md:h-[70vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                        </div>
                    </div> */}







                </section>
            </main>
        </>
    );
}