import Head from "next/head";
import Image from "next/image";
import React, { useEffect, useState } from "react";


export default function Home() {
    React.useEffect(() => {
        window.addEventListener('scroll', changeColor)
    }, []);

    const [color, setColor] = useState(false)

    const changeColor = () => {
        if (window.scrollY >= window.innerHeight) {
            setColor(true)
        } else {
            setColor(false)
        }
    }

    const bgstyle = {
        backgroundImage: "url('/media/experienceshero.jpg')",
        height: '100vh',
        backgroundAttachment: 'fixed'
    }

    const itemstyle1 = {
        backgroundImage: "url('/media/experiencesbg.png')",
        height: '100%',
    }
    const itemstyle2 = {
        backgroundImage: "url('/media/experiencesbgi.png')",
        height: '100%',
    }


    return (
        <>
            <Head>
                <title>Incoming India | Contact</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <section className="text-black">
                    <div className="bg-cover bg-center bg-no-repeat flex items-center justify-center" style={bgstyle}>
                        <div className="text-center px-2">
                            <h1 className="md:text-6xl text-4xl font-poppins font-semibold tracking-wide text-white hero-shadow">Experience India</h1>
                            <p className="font-poppins font-semibold md:text-2xl max-w-screen-md pt-2 text-[1.2rem] text-white hero-shadow">Discover the vibrant colors, flavors, and traditions of India's rich cultural tapestry - a journey you'll never forget!</p>
                        </div>
                    </div>

                    <nav className={`${color ? ' fixed top-[60px] lg:h-[30px] h-[50px] bg-white right-0 left-0' : 'h-[60px]'} bg-white z-10 w-[100full] flex justify-center items-center font-serifjp`}>
                        <ul className='lg:flex flex-row justify-center md:space-x-12 text-sm sm:text-md lg:text-lg'>
                            <div className='justify-center flex '>
                                <div className='lg:space-x-12 space-x-5 flex'>
                                    <li className={` cursor-pointer hover:text-orange-500 hover:border-b-2 hover:border-b-orange-500`}> <a href="#1">Documents</a></li>
                                    <li className={` cursor-pointer hover:text-orange-500 hover:border-b-2 hover:border-b-orange-500`}><a href="#2">Traditions</a></li>
                                    <li className={` cursor-pointer hover:text-orange-500 hover:border-b-2 hover:border-b-orange-500`}> <a href="#3">Protection</a></li>
                                </div>
                            </div>
                            <div className=' lg:space-x-12 space-x-5 flex'>
                                <li className={`cursor-pointer hover:text-orange-500 hover:border-b-2 hover:border-b-orange-500`} > <a href="#4">Communication</a></li>
                                <li className={`cursor-pointer hover:text-orange-500 hover:border-b-2 hover:border-b-orange-500`} > <a href="#5">Transit</a></li>
                                <li className={`cursor-pointer hover:text-orange-500 hover:border-b-2 hover:border-b-orange-500`} > <a href="#6">Recreation</a></li>
                                <li className={`cursor-pointer hover:text-orange-500 hover:border-b-2 hover:border-b-orange-500`} > <a href="#7">Cuisine</a></li>
                            </div>
                        </ul>
                    </nav >



                    <div style={itemstyle1} className=" bg-blue-300   bg-cover bg-center bg-no-repeat ">
                        <div className="flex-row md:flex">
                            <img src='/media/honeymoon.jpg' className=" object-cover md:h-[80vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                            <div className="w-full md:w-1/2 px-2 ">
                                <h1 className="text-center py-10 text-3xl md:text-5xl text-black hero- font-poppins font-semibold ">Honeymoon Packages</h1>
                                <div className="flex justify-center">
                                    <div className="border-b-[3px] border-b-indigo-900 w-1/2"></div>
                                </div>

                            </div>
                        </div>
                    </div>


                    <div style={itemstyle2} className="h-[50vh] bg-blue-300   bg-cover bg-center bg-no-repeat">
                        <div className="flex-row md:flex">
                            <div className="w-full md:w-1/2 px-2 ">
                                <h1 className="text-center py-10 text-3xl md:text-5xl text-black hero- font-poppins font-semibold">Himalayas & Mountains</h1>
                            </div>
                            <img src='/media/mountains.jpg' className=" object-cover md:h-[80vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                        </div>
                    </div>


                    <div style={itemstyle1} className=" bg-blue-300   bg-cover bg-center bg-no-repeat ">
                        <div className="flex-row md:flex">
                            <img src='/media/train.jpg' className=" object-cover md:h-[80vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                            <div className="w-full md:w-1/2 px-2 ">
                                <h1 className="text-center py-10 text-3xl md:text-5xl text-black hero- font-poppins font-semibold">Train Packages</h1>
                            </div>
                        </div>
                    </div>


                    <div style={itemstyle2} className="h-[50vh] bg-blue-300   bg-cover bg-center bg-no-repeat">
                        <div className="flex-row md:flex">
                            <div className="w-full md:w-1/2 px-2 ">
                                <h1 className="text-center py-10 text-3xl md:text-5xl text-black hero- font-poppins font-semibold">Forts, Palaces and Temples</h1>
                            </div>
                            <img src='/media/forts.jpg' className=" object-cover md:h-[80vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                        </div>
                    </div>


                    <div style={itemstyle1} className=" bg-blue-300   bg-cover bg-center bg-no-repeat ">
                        <div className="flex-row md:flex">
                            <img src='/media/wildlife.jpg' className=" object-cover md:h-[80vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                            <div className="w-full md:w-1/2 px-2 ">
                                <h1 className="text-center py-10 text-3xl md:text-5xl text-black hero- font-poppins font-semibold">Wildlife Experiences</h1>
                            </div>
                        </div>
                    </div>


                    <div style={itemstyle2} className="h-[50vh] bg-blue-300   bg-cover bg-center bg-no-repeat">
                        <div className="flex-row md:flex">
                            <div className="w-full md:w-1/2 px-2 ">
                                <h1 className="text-center py-10 text-3xl md:text-5xl text-black hero- font-poppins font-semibold">Inner Peace</h1>
                            </div>
                            <img src='/media/yoga.jpg' className=" object-cover md:h-[80vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                        </div>
                    </div>


                    <div style={itemstyle1} className=" bg-blue-300   bg-cover bg-center bg-no-repeat ">
                        <div className="flex-row md:flex">
                            <img src='/media/beech.jpg' className=" object-cover md:h-[80vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                            <div className="w-full md:w-1/2 px-2 ">
                                <h1 className="text-center py-10 text-3xl md:text-5xl text-black hero- font-poppins font-semibold">Beeches & Islands</h1>
                            </div>
                        </div>
                    </div>


                    <div style={itemstyle2} className="h-[50vh] bg-blue-300   bg-cover bg-center bg-no-repeat">
                        <div className="flex-row md:flex">
                            <div className="w-full md:w-1/2 px-2 ">
                                <h1 className="text-center py-10 text-3xl md:text-5xl text-black hero- font-poppins font-semibold">Family Time & Travel</h1>
                            </div>
                            <img src='/media/family.jpg' className=" object-cover md:h-[80vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                        </div>
                    </div>


                    <div style={itemstyle1} className=" bg-blue-300   bg-cover bg-center bg-no-repeat ">
                        <div className="flex-row md:flex">
                            <img src='/media/food.jpg' className=" object-cover md:h-[80vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                            <div className="w-full md:w-1/2 px-2 ">
                                <h1 className="text-center py-10 text-3xl md:text-5xl text-black hero- font-poppins font-semibold">Delicious Indian Cuisine</h1>
                            </div>
                        </div>
                    </div>


                    <div style={itemstyle2} className="h-[50vh] bg-blue-300   bg-cover bg-center bg-no-repeat">
                        <div className="flex-row md:flex">
                            <div className="w-full md:w-1/2 px-2 ">
                                <h1 className="text-center py-10 text-3xl md:text-5xl text-black hero- font-poppins font-semibold">Lakes & Houseboats</h1>
                            </div>
                            <img src='/media/houseboats.jpg' className=" object-cover md:h-[80vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                        </div>
                    </div>


                    {/* <div style={itemstyle1} className=" bg-blue-300   bg-cover bg-center bg-no-repeat ">
                        <div className="flex-row md:flex">
                            <img src='/media/food.jpg' className=" object-cover md:h-[80vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                            <div className="w-full md:w-1/2 px-2 ">
                                <h1 className="text-center py-10 text-3xl md:text-5xl text-black hero- font-poppins font-semibold">Honeymoon Packages</h1>
                            </div>
                        </div>
                    </div> */}


                    {/* <div style={itemstyle2} className="h-[50vh] bg-blue-300   bg-cover bg-center bg-no-repeat">
                        <div className="flex-row md:flex">
                            <div className="w-full md:w-1/2 px-2 ">
                                <h1 className="text-center py-10 text-3xl md:text-5xl text-black hero- font-poppins font-semibold">Honeymoon Packages</h1>
                            </div>
                            <img src='/media/mountains.jpg' className=" object-cover md:h-[80vh]  w-full md:w-1/2 sm:h-[50vh] h-[40vh]" />
                        </div>
                    </div> */}







                </section>
            </main>
        </>
    );
}