import Head from "next/head";
import Navbar from "@/components/Navbar";
import Footer from "../components/Footer";
import Hero from "@/components/Hero";
import Welcome from "@/components/Welcome";
import Explore from "@/components/Explore";
import Review from "../components/Review";
import Section from "@/components/Section";
import Insights from "@/components/Insights";
import Itenary from "@/components/pages/Itenaries";
import Test from "@/components/Test";




export default function Home() {
  return (
    <>
      <Head>
        <title>Incoming India</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      {/* <Navbar /> */}
      <main id="mainCont">
        <Hero />
        <Welcome />
        <Itenary />
        <Explore />
        <Section />
        <Review />
      </main>
      {/* <Footer /> */}
    </>
  );
  {/* <Test /> */ }
}
