import Head from "next/head";
import Image from "next/image";
import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Footer from "../components/Footer";
import Review from "../components/Review"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Review />
        <Footer />
      </main>
    </>
  );
}
