import Head from "next/head";
import Navbar from "@/components/Navbar";
import Footer from "../components/Footer";
import Indhero from "@/components/india/Indhero";
import Indnav from "@/components/india/Indnav";
import Indexp from "@/components/india/Indexp";
import Moretovisit from "@/components/india/Moretovisit";
import Indgallery from "@/components/india/Indgallery";




export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                {/* <Navbar /> */}
                <Indhero />
                <Indnav />
                <Indexp />
                <Indgallery />
                <Moretovisit />
                {/* <Footer /> */}
            </main>
        </>
    );
}
