import Head from "next/head";
import Navbar from "@/components/Navbar";
import Footer from "../components/Footer";
import Indhero from "@/components/india/Indhero";
import Indnav from "@/components/india/Indnav";




export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Navbar />
                <Indhero />
                <Indnav />
                <Footer />
            </main>
        </>
    );
}
