import Insights from "@/components/Insights";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Head from "next/head";

export default function Home() {
    return (
        <>
            <Head>
                <title>Incoming India | Insights</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                {/* <Navbar /> */}
                <Insights />
                {/* <Footer /> */}
            </main>
        </>
    );
}