import Lankaexp from "@/components/lanka/Lankaexp";
import Lankahero from "@/components/lanka/Lankahero";
import Lankanav from "@/components/lanka/Lankanav";
import Moretovisitlanka from "@/components/lanka/Moretovisitlanka";
import Head from "next/head";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Lankagallery from "@/components/lanka/Lankagallery";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>

                {/* <Navbar /> */}
                <Lankahero />
                <Lankanav />
                <Lankaexp />
                <Lankagallery />
                <Moretovisitlanka />
                {/* <Footer /> */}
            </main>
        </>
    );
}