// import Malexp from "@/components/maldives/Malexp";
// import Malhero from "@/components/maldives/Malhero";
// import Malnav from "@/components/maldives/Malnav";
// import Moretovisitmal from "@/components/maldives/Moretovisitmal";
// import Head from "next/head";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";

// export default function Home() {
//     return (
//         <>
//             <Head>
//                 <title>Create Next App</title>
//                 <meta name="description" content="Generated by create next app" />
//                 <meta name="viewport" content="width=device-width, initial-scale=1" />
//                 <link rel="icon" href="/favicon.ico" />
//             </Head>
//             <main>

//                 <Navbar />
//                 <Malhero />
//                 <Malnav />
//                 <Malexp />
//                 <Moretovisitmal />
//                 <Footer />
//             </main>
//         </>
//     );
// }